services:
  # Web Service
  - type: web
    name: edumosaic-backend
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: edumosaic-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: edumosaic-redis
          type: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11"
    healthCheckPath: /health
    autoDeploy: true

databases:
  # PostgreSQL Database
  - name: edumosaic-db
    databaseName: edumosaic
    user: edumosaic_user
    plan: free

# Redis Instance (defined separately as a service)
services:
  - type: redis
    name: edumosaic-redis
    plan: free
    ipAllowList: []